### ISSUE TITLE
Dev container errors

### ISSUE THREAD

**Issue by dwhiteddsoft** [eclipse/chariott#42]
## Expected Behavior
Dev container should open

## Current Behavior
Dev container fails to open

## Steps to Reproduce
1. Fresh OS install
2. Install Docker desktop
3. Install VS Code
4. Clone repo
5. Open VS Code
6. Re-open in dev container
7. Fails

## Context (Environment)
OS: Edition: Windows 11 Pro Version - 22H2
OS build: 22621.819
Experience: Windows Feature Experience Pack 1000.22636.1000.0
WSL Distributor ID: Ubuntu
WSL Description:    Ubuntu 22.04.1 LTS
WSL Release:        22.04
VS Code: 1.73.1

## Logs
I will just paste the last few lines here:

```bash
 => [dev_container_auto_added_stage_label 2/7] RUN apt-get update && exp  17.6s
 => [dev_container_auto_added_stage_label 3/7] RUN mkdir /usr/bin/grpcurl  2.4s
 => [dev_container_auto_added_stage_label 4/7] RUN PREFIX="/usr/local" &&  3.8s
 => [dev_container_auto_added_stage_label 5/7] RUN set -x && curl -sSL h  97.9s
 => [dev_container_auto_added_stage_label 6/7] COPY ../rust-toolchain .    0.1s
 => ERROR [dev_container_auto_added_stage_label 7/7] RUN rustup override   0.7s
------
 > [dev_container_auto_added_stage_label 7/7] RUN rustup override set $(cat rust
-toolchain) &&     rustup component add clippy &&     rustup component add rustf
mt:
' is not installedolchain '1.65
------
[2022-11-14T20:20:09.967Z] ERROR: failed to solve: executor failed running [/bin/sh -c rustup override set
$(cat rust-toolchain) &&     rustup component add clippy &&     rustup component
 add rustfmt]: exit code: 1
[2022-11-14T20:20:10.260Z] Stop (325731 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\ddsof\AppData\Local\Temp\devcontainercli\container-features\0.23.2-1668456883460\Dockerfile-with-features -t vsc-chariott-8b02106d40e7c260ddf8f2102f808fe2 --target dev_containers_target_stage --build-arg DOTNET_VERSION=6.0.301 --build-arg VARIANT=bullseye --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\Users\ddsof\source\repos\chariott
[2022-11-14T20:20:10.272Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\ddsof\AppData\Local\Temp\devcontainercli\container-features\0.23.2-1668456883460\Dockerfile-with-features -t vsc-chariott-8b02106d40e7c260ddf8f2102f808fe2 --target dev_containers_target_stage --build-arg DOTNET_VERSION=6.0.301 --build-arg VARIANT=bullseye --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\Users\ddsof\source\repos\chariott
[2022-11-14T20:20:10.273Z]     at doe (c:\Users\ddsof\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:1888:1635)
[2022-11-14T20:20:10.273Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-11-14T20:20:10.274Z]     at async pF (c:\Users\ddsof\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:1887:1973)
[2022-11-14T20:20:10.274Z]     at async eT (c:\Users\ddsof\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:1887:901)
[2022-11-14T20:20:10.274Z]     at async voe (c:\Users\ddsof\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:1893:2049)
[2022-11-14T20:20:10.274Z]     at async Xf (c:\Users\ddsof\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:1893:3212)
[2022-11-14T20:20:10.275Z]     at async Jae (c:\Users\ddsof\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:2013:15058)
[2022-11-14T20:20:10.275Z]     at async Wae (c:\Users\ddsof\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:2013:14812)
[2022-11-14T20:20:10.316Z] Stop (330666 ms): Run: C:\Users\ddsof\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\ddsof\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\ddsof\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\ddsof\source\repos\chariott --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\ddsof\source\repos\chariott --log-level debug --log-format json --config c:\Users\ddsof\source\repos\chariott\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-14T20:20:10.319Z] Exit code 1
[2022-11-14T20:20:10.340Z] Command failed: C:\Users\ddsof\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\ddsof\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\ddsof\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\ddsof\source\repos\chariott --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\ddsof\source\repos\chariott --log-level debug --log-format json --config c:\Users\ddsof\source\repos\chariott\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-14T20:20:10.340Z] Exit code 1
```

**Comment by dariuszparys** [comment]
Thanks for reporting this, indeed this is the instruction failing on Windows based source code repository.

```Dockerfile
RUN rustup override set $(cat rust-toolchain) && \
    rustup component add clippy && \
    rustup component add rustfmt
```

In general, we recommend checking out the source inside the WSL2 distribution and starting the vscode from that path directly. This allows the devcontainer to build correctly.

**Comment by atifaziz** [comment]
This is due to a CR in the file. It's simple to get rid of with a `sed`.
